import Head from 'next/head';

import { Nav } from 'Components';

export default function Blog() {
	return (
		<>
			<Head>
				<title>Blog | Simon Rose</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Nav />

			<main className="container mx-auto"></main>

			<footer></footer>
		</>
	);
}
