import type { NextPage } from 'next';
import Head from 'next/head';

import { Nav } from 'Components';

const Blog: NextPage = () => (
	<>
		<Head>
			<title>Blog | Simon Rose</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<Nav />

		<main className="container mx-auto" />

		<footer />
	</>
);

export default Blog;
