/* eslint-disable max-len */
import type { NextPage } from 'next';
import Head from 'next/head';

import { Layout, Position, Profile } from 'Components';
import { experiences } from 'Content';

const Home: NextPage = () => (
	<Layout>
		<Head>
			<title>Home | Simon Rose</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<main className="container mx-auto mt-12 flex flex-col gap-14">
			<Profile />
			<hr className="border-gray-400" />
			<div className="flex flex-col gap-4">
				<h2 className="text-2xl flex">Experience</h2>
				<div className="flex flex-col gap-20">
					{experiences.map(ex => (
						<Position information={ex} />
					))}
				</div>
			</div>
		</main>
	</Layout>
);

export default Home;
