import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>Home | Simon Rose</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container mx-auto">
				<h1>Simon Rose</h1>
			</main>

			<footer></footer>
		</>
	);
}
