import Head from 'next/head';

import { Layout, Profile } from 'Components';

export default function Home() {
	return (
		<Layout>
			<Head>
				<title>Home | Simon Rose</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container mx-auto mt-12">
				<Profile />

				<div className="flex">
					<h2 className="w-48">Experience</h2>
					<div></div>
				</div>
			</main>
		</Layout>
	);
}
